# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

namespace :cema do
	desc "Make Ctags for ruby application (Windows)"
	task :ctags do
		system "dir /b /S *.rb | ctags -f .tags -L -"
		if File.exist? './Gemfile'
			require 'bundler'
			paths = Bundler.load.specs.map(&:full_gem_path).join(' ')
			system "ctags -R -f .gemtags #{paths}"
		end
	end
end